spring:
  application:
    name: next75
  h2:
   console:
     path: /h2-console
     enabled: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:next75-dev
    username: admin_viewer
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  sql:
    init:
      mode: never
server:
  port: 8009