spring:
  application:
    name: next75

  datasource:
    url: jdbc:postgresql://localhost:5432/next75-dev?createDatabaseIfNotExist=true
    username: postgres
    password: READme2025$

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  sql:
#    init:
#      mode: always